// 自动生成 —— 请勿手改。由 scripts/stepfun/build-manifest.mjs 扫描 public/story-art 与 public/story-voice 产出。
// 键: "<gameId>/<sceneId>" → 静态资源根路径。GameView/playModel 据此把真实配图与旁白配音挂到场景上。
export const ART: Record<string, string> = {
  "chenshi/age14": "/story-art/chenshi/age14.png",
  "chenshi/age21": "/story-art/chenshi/age21.png",
  "chenshi/age28_office": "/story-art/chenshi/age28_office.png",
  "chenshi/age28_south": "/story-art/chenshi/age28_south.png",
  "chenshi/age7": "/story-art/chenshi/age7.png",
  "musk/m_leave": "/story-art/musk/m_leave.png",
  "musk/m_paypal": "/story-art/musk/m_paypal.png",
  "musk/m_penn": "/story-art/musk/m_penn.png",
  "musk/m_stanford": "/story-art/musk/m_stanford.png",
  "musk/m_start": "/story-art/musk/m_start.png",
  "musk/m_xcom": "/story-art/musk/m_xcom.png",
  "musk/m_zip2": "/story-art/musk/m_zip2.png",
  "musk/m_zip2_hold": "/story-art/musk/m_zip2_hold.png",
  "musk/m_zip2_sell": "/story-art/musk/m_zip2_sell.png",
  "simaqian/c_brush": "/story-art/simaqian/c_brush.png",
  "simaqian/c_life_death": "/story-art/simaqian/c_life_death.png",
  "simaqian/c_oath": "/story-art/simaqian/c_oath.png",
  "simaqian/c_start_book": "/story-art/simaqian/c_start_book.png",
  "simaqian/s_crime_1": "/story-art/simaqian/s_crime_1.png",
  "simaqian/s_crime_2": "/story-art/simaqian/s_crime_2.png",
  "simaqian/s_death_1": "/story-art/simaqian/s_death_1.png",
  "simaqian/s_endure_1": "/story-art/simaqian/s_endure_1.png",
  "simaqian/s_endure_2": "/story-art/simaqian/s_endure_2.png",
  "simaqian/s_hide_1": "/story-art/simaqian/s_hide_1.png",
  "simaqian/s_hide_2": "/story-art/simaqian/s_hide_2.png",
  "simaqian/s_hide_3": "/story-art/simaqian/s_hide_3.png",
  "simaqian/s_inherit_1": "/story-art/simaqian/s_inherit_1.png",
  "simaqian/s_inherit_2": "/story-art/simaqian/s_inherit_2.png",
  "simaqian/s_safe_1": "/story-art/simaqian/s_safe_1.png",
  "simaqian/s_taishi_1": "/story-art/simaqian/s_taishi_1.png",
  "simaqian/s_youth_1": "/story-art/simaqian/s_youth_1.png",
  "simaqian/s_youth_2": "/story-art/simaqian/s_youth_2.png",
  "sushi/s_beigui": "/story-art/sushi/s_beigui.png",
  "sushi/s_chibi": "/story-art/sushi/s_chibi.png",
  "sushi/s_choose_chibi": "/story-art/sushi/s_choose_chibi.png",
  "sushi/s_choose_court": "/story-art/sushi/s_choose_court.png",
  "sushi/s_choose_huizhou": "/story-art/sushi/s_choose_huizhou.png",
  "sushi/s_choose_path": "/story-art/sushi/s_choose_path.png",
  "sushi/s_choose_wutai": "/story-art/sushi/s_choose_wutai.png",
  "sushi/s_choose_xining": "/story-art/sushi/s_choose_xining.png",
  "sushi/s_danzhou": "/story-art/sushi/s_danzhou.png",
  "sushi/s_fengxiang": "/story-art/sushi/s_fengxiang.png",
  "sushi/s_finale": "/story-art/sushi/s_finale.png",
  "sushi/s_hangzhou": "/story-art/sushi/s_hangzhou.png",
  "sushi/s_hangzhou2": "/story-art/sushi/s_hangzhou2.png",
  "sushi/s_huangzhou": "/story-art/sushi/s_huangzhou.png",
  "sushi/s_huangzhou2": "/story-art/sushi/s_huangzhou2.png",
  "sushi/s_huizhou": "/story-art/sushi/s_huizhou.png",
  "sushi/s_mizhou": "/story-art/sushi/s_mizhou.png",
  "sushi/s_return_court": "/story-art/sushi/s_return_court.png",
  "sushi/s_start": "/story-art/sushi/s_start.png",
  "sushi/s_start2": "/story-art/sushi/s_start2.png",
  "sushi/s_wutai": "/story-art/sushi/s_wutai.png",
  "sushi/s_xining": "/story-art/sushi/s_xining.png",
  "wangyangming/w_gezhu_event": "/story-art/wangyangming/w_gezhu_event.png",
  "wangyangming/w_gezhu_in": "/story-art/wangyangming/w_gezhu_in.png",
  "wangyangming/w_keju_in": "/story-art/wangyangming/w_keju_in.png",
  "wangyangming/w_start": "/story-art/wangyangming/w_start.png",
  "wuzetian/c_chengjun": "/story-art/wuzetian/c_chengjun.png",
  "wuzetian/c_feihou": "/story-art/wuzetian/c_feihou.png",
  "wuzetian/c_gongzhu": "/story-art/wuzetian/c_gongzhu.png",
  "wuzetian/c_xuhuai": "/story-art/wuzetian/c_xuhuai.png",
  "wuzetian/s_dayun": "/story-art/wuzetian/s_dayun.png",
  "wuzetian/s_dengji": "/story-art/wuzetian/s_dengji.png",
  "wuzetian/s_eulou": "/story-art/wuzetian/s_eulou.png",
  "wuzetian/s_feihou": "/story-art/wuzetian/s_feihou.png",
  "wuzetian/s_fengshan": "/story-art/wuzetian/s_fengshan.png",
  "wuzetian/s_furui": "/story-art/wuzetian/s_furui.png",
  "wuzetian/s_ganye": "/story-art/wuzetian/s_ganye.png",
  "wuzetian/s_huigong": "/story-art/wuzetian/s_huigong.png",
  "wuzetian/s_jixu": "/story-art/wuzetian/s_jixu.png",
  "wuzetian/s_lion": "/story-art/wuzetian/s_lion.png",
  "wuzetian/s_open": "/story-art/wuzetian/s_open.png",
  "wuzetian/s_shangguan": "/story-art/wuzetian/s_shangguan.png",
  "wuzetian/s_taizi": "/story-art/wuzetian/s_taizi.png",
  "wuzetian/s_xuhuai": "/story-art/wuzetian/s_xuhuai.png",
  "wuzetian/s_zhaoyi": "/story-art/wuzetian/s_zhaoyi.png",
  "yingzheng/c_fenshu": "/story-art/yingzheng/c_fenshu.png",
  "yingzheng/c_jianglue": "/story-art/yingzheng/c_jianglue.png",
  "yingzheng/c_junxian": "/story-art/yingzheng/c_junxian.png",
  "yingzheng/c_lichu": "/story-art/yingzheng/c_lichu.png",
  "yingzheng/c_qinzheng": "/story-art/yingzheng/c_qinzheng.png",
  "yingzheng/c_zhuke": "/story-art/yingzheng/c_zhuke.png",
  "yingzheng/s_changcheng": "/story-art/yingzheng/s_changcheng.png",
  "yingzheng/s_chenghuang": "/story-art/yingzheng/s_chenghuang.png",
  "yingzheng/s_fengshan": "/story-art/yingzheng/s_fengshan.png",
  "yingzheng/s_fenshu": "/story-art/yingzheng/s_fenshu.png",
  "yingzheng/s_jianzhuke": "/story-art/yingzheng/s_jianzhuke.png",
  "yingzheng/s_jingke": "/story-art/yingzheng/s_jingke.png",
  "yingzheng/s_jiwei": "/story-art/yingzheng/s_jiwei.png",
  "yingzheng/s_kengru": "/story-art/yingzheng/s_kengru.png",
  "yingzheng/s_laoai": "/story-art/yingzheng/s_laoai.png",
  "yingzheng/s_miehan": "/story-art/yingzheng/s_miehan.png",
  "yingzheng/s_mougong": "/story-art/yingzheng/s_mougong.png",
  "yingzheng/s_open": "/story-art/yingzheng/s_open.png",
  "yingzheng/s_qiuxian": "/story-art/yingzheng/s_qiuxian.png",
  "yingzheng/s_return": "/story-art/yingzheng/s_return.png",
  "yingzheng/s_shaqiu": "/story-art/yingzheng/s_shaqiu.png",
  "yingzheng/s_tinglun": "/story-art/yingzheng/s_tinglun.png",
  "yingzheng/s_tongyi": "/story-art/yingzheng/s_tongyi.png",
  "yingzheng/s_yitong": "/story-art/yingzheng/s_yitong.png",
  "yingzheng/s_zhengguo": "/story-art/yingzheng/s_zhengguo.png",
  "zhangqian/shouming1": "/story-art/zhangqian/shouming1.png",
  "zhenghe/choice_guicheng": "/story-art/zhenghe/choice_guicheng.png",
  "zhenghe/choice_jinghai": "/story-art/zhenghe/choice_jinghai.png",
  "zhenghe/choice_qihang": "/story-art/zhenghe/choice_qihang.png",
  "zhenghe/choice_tongyu": "/story-art/zhenghe/choice_tongyu.png",
  "zhenghe/choice_xilan": "/story-art/zhenghe/choice_xilan.png",
  "zhenghe/huerm1": "/story-art/zhenghe/huerm1.png",
  "zhenghe/huerm3": "/story-art/zhenghe/huerm3.png",
  "zhenghe/huijing1": "/story-art/zhenghe/huijing1.png",
  "zhenghe/huijing2": "/story-art/zhenghe/huijing2.png",
  "zhenghe/huijing3": "/story-art/zhenghe/huijing3.png",
  "zhenghe/manci2": "/story-art/zhenghe/manci2.png",
  "zhenghe/nanhai1": "/story-art/zhenghe/nanhai1.png",
  "zhenghe/nanhai2": "/story-art/zhenghe/nanhai2.png",
  "zhugeliang/z_beifa_choice": "/story-art/zhugeliang/z_beifa_choice.png",
  "zhugeliang/z_chibi_choice": "/story-art/zhugeliang/z_chibi_choice.png",
  "zhugeliang/z_chibi_envoy": "/story-art/zhugeliang/z_chibi_envoy.png",
  "zhugeliang/z_chibi_fire": "/story-art/zhugeliang/z_chibi_fire.png",
  "zhugeliang/z_chibi_lead": "/story-art/zhugeliang/z_chibi_lead.png",
  "zhugeliang/z_chushi": "/story-art/zhugeliang/z_chushi.png",
  "zhugeliang/z_end_gate": "/story-art/zhugeliang/z_end_gate.png",
  "zhugeliang/z_jieting": "/story-art/zhugeliang/z_jieting.png",
  "zhugeliang/z_jieting_fall": "/story-art/zhugeliang/z_jieting_fall.png",
  "zhugeliang/z_jingzhou": "/story-art/zhugeliang/z_jingzhou.png",
  "zhugeliang/z_nanzheng": "/story-art/zhugeliang/z_nanzheng.png",
  "zhugeliang/z_rushu_law": "/story-art/zhugeliang/z_rushu_law.png",
  "zhugeliang/z_rushu_settle": "/story-art/zhugeliang/z_rushu_settle.png",
  "zhugeliang/z_sangu": "/story-art/zhugeliang/z_sangu.png",
  "zhugeliang/z_start": "/story-art/zhugeliang/z_start.png",
  "zhugeliang/z_tuogu_choice": "/story-art/zhugeliang/z_tuogu_choice.png",
  "zhugeliang/z_tuogu_lead": "/story-art/zhugeliang/z_tuogu_lead.png",
  "zhugeliang/z_wuzhang_choice": "/story-art/zhugeliang/z_wuzhang_choice.png",
  "zhugeliang/z_wuzhang_lead": "/story-art/zhugeliang/z_wuzhang_lead.png",
  "zhugeliang/z_xingluo": "/story-art/zhugeliang/z_xingluo.png",
  "zhugeliang/z_yiling": "/story-art/zhugeliang/z_yiling.png",
  "zhugeliang/z_yongren": "/story-art/zhugeliang/z_yongren.png",
  "zhugeliang/z_zaibei": "/story-art/zhugeliang/z_zaibei.png",
  "zhugeliang/z_zhanmasu": "/story-art/zhugeliang/z_zhanmasu.png",
  "zhuyuanzhang/z_beg_event": "/story-art/zhuyuanzhang/z_beg_event.png",
  "zhuyuanzhang/z_join_in": "/story-art/zhuyuanzhang/z_join_in.png",
  "zhuyuanzhang/z_marry_in": "/story-art/zhuyuanzhang/z_marry_in.png",
  "zhuyuanzhang/z_plague_bury": "/story-art/zhuyuanzhang/z_plague_bury.png",
  "zhuyuanzhang/z_plague_in": "/story-art/zhuyuanzhang/z_plague_in.png",
  "zhuyuanzhang/z_start": "/story-art/zhuyuanzhang/z_start.png",
  "zhuyuanzhang/z_temple_in": "/story-art/zhuyuanzhang/z_temple_in.png"
};

export const VOICE: Record<string, string> = {
  "chenshi/age14": "/story-voice/chenshi/age14.mp3",
  "chenshi/age7": "/story-voice/chenshi/age7.mp3",
  "simaqian/c_defend_ling": "/story-voice/simaqian/c_defend_ling.mp3",
  "simaqian/c_grand_tour": "/story-voice/simaqian/c_grand_tour.mp3",
  "simaqian/c_life_death": "/story-voice/simaqian/c_life_death.mp3",
  "simaqian/c_oath": "/story-voice/simaqian/c_oath.mp3",
  "simaqian/c_start_book": "/story-voice/simaqian/c_start_book.mp3",
  "simaqian/s_crime_1": "/story-voice/simaqian/s_crime_1.mp3",
  "simaqian/s_crime_2": "/story-voice/simaqian/s_crime_2.mp3",
  "simaqian/s_endure_1": "/story-voice/simaqian/s_endure_1.mp3",
  "simaqian/s_inherit_1": "/story-voice/simaqian/s_inherit_1.mp3",
  "simaqian/s_inherit_2": "/story-voice/simaqian/s_inherit_2.mp3",
  "simaqian/s_safe_1": "/story-voice/simaqian/s_safe_1.mp3",
  "simaqian/s_taishi_1": "/story-voice/simaqian/s_taishi_1.mp3",
  "simaqian/s_taishi_2": "/story-voice/simaqian/s_taishi_2.mp3",
  "simaqian/s_war_1": "/story-voice/simaqian/s_war_1.mp3",
  "simaqian/s_war_2": "/story-voice/simaqian/s_war_2.mp3",
  "simaqian/s_youth_1": "/story-voice/simaqian/s_youth_1.mp3",
  "simaqian/s_youth_2": "/story-voice/simaqian/s_youth_2.mp3",
  "yingzheng/s_jiwei": "/story-voice/yingzheng/s_jiwei.mp3",
  "yingzheng/s_laoai": "/story-voice/yingzheng/s_laoai.mp3",
  "yingzheng/s_open": "/story-voice/yingzheng/s_open.mp3",
  "yingzheng/s_return": "/story-voice/yingzheng/s_return.mp3"
};

export const VIDEO: Record<string, string> = {};

export function artFor(gameId: string, sceneId: string): string | undefined {
  return ART[gameId + "/" + sceneId];
}
export function voiceFor(gameId: string, sceneId: string): string | undefined {
  return VOICE[gameId + "/" + sceneId];
}
export function videoFor(gameId: string, sceneId: string): string | undefined {
  return VIDEO[gameId + "/" + sceneId];
}
